version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.12.0
  helm: circleci/helm@1.2.0

commands:
  checkout_and_decrypt:
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install git-crypt
#      - run: echo "${GIT_CRYPT_KEY}" | base64 -d > git-crypt.key
#      - run: git-crypt unlock git-crypt.key

jobs:
  build-test-package:
    docker:
      - image: cimg/openjdk:11.0.12
        environment:
          JAVA_ENV: test
    steps:
      - checkout
      - run:
          name: Build, test and package jar
          command: |
            ./gradlew sonarqube -Dsonar.projectKey=crime-means-assessment -Dsonar.host.url=http://sonarqube.aws.ssvs.legalservices.gov.uk -Dsonar.login=${SONARQUBE_TOKEN}
          when: always      
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

workflows:
  version: 2
  test-build-master:
    jobs:
      - build-test-package:
          filters:
            branches:
              only:
                - master

  test-branch:
    jobs:
      - build-test-package:
        filters:
          branches:
            ignore:
              - master

  build-deploy-branch:
    jobs:
      - branch-build-approval:
          type: approval
          filters:
            branches:
              ignore:
                - master