{{- if .Values.caSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.caSecret.name }}
  labels:
    {{- include "laa-crime-means-assessment.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Files.Get .Values.caSecret.ca_crt_file | b64enc }}
{{- end }}
