apiVersion: v1
kind: Service
metadata:
  name: {{ include "laa-crime-means-assessment.fullname" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: true
  labels:
    {{- include "laa-crime-means-assessment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if not (eq (toString .Values.actuator.port) "http") }}
    - port: {{ .Values.actuator.port }}
      targetPort: actuator
      protocol: TCP
      name: actuator
    {{- end }}      
  selector:
    {{- include "laa-crime-means-assessment.selectorLabels" . | nindent 4 }}
