apiVersion: v1
kind: Service
metadata:
  name: {{ include "laa-crime-mean-assessment.fullname" . }}
  labels:
    {{- include "laa-crime-mean-assessment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.metrics_service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "laa-crime-mean-assessment.selectorLabels" . | nindent 4 }}
