server:
  port: 8080

maatApi:
  oauth.enabled: false
  url: ${MAAT_API_URL}

spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST_PORT}/${DATASOURCE_DBNAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 3600000

  security:
    oauth2:
      client:
        provider:
          maatapi:
            tokenUri: ${MAAT_API_OAUTH_URL}
        registration:
          maatapi:
            clientId: ${MAAT_API_OAUTH_CLIENT_ID}
            clientSecret: ${MAAT_API_OAUTH_CLIENT_SECRET}
            authorizationGrantType: client_credentials

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

springdoc:
  packagesToScan: uk.gov.justice.laa.crime.meansassessment
  show-actuator: true
  api-docs:
    path: /crime-means-assessment
    enabled: true

  swagger-ui:
    path: /open-api/docs.html
    enabled: true
    operationsSorter: method

sentry:
  dsn: https://27fa5ff9451241cc8cd9aa85dac09e60@o345774.ingest.sentry.io/5372961
  environment: ${SENTRY_ENV}
  release: 1.1.0
  servername: aws-eks-container
  send-default-pii: true
  logging:
    minimum-breadcrumb-level: info
    minimum-event-level: info
    enabled: true
  attach-stacktrace: true


version: 0.0.1
