server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

management:
  server:
    port: 8096
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

maatApi:
  oAuthEnabled: true
  baseUrl: ${MAAT_API_BASE_URL}
  assessments-domain: /api/internal/v1/assessment

  post-processing-url: ${maatApi.assessments-domain}/post-processing

  validation-endpoints:
    role-action-url: ${maatApi.assessments-domain}/authorization/users/{username}/actions/{action}
    new-work-reason-url: ${maatApi.assessments-domain}/authorization/users/{username}/work-reasons/{nworCode}
    reservations-url: ${maatApi.assessments-domain}/authorization/users/{username}/reservations/{reservationId}/sessions/{sessionId}
    outstanding-assessments-url: ${maatApi.assessments-domain}/financial-assessments/check-outstanding/{repId}
  financial-assessment-endpoints:
    create-url: ${maatApi.assessments-domain}/financial-assessments/
    update-url: ${maatApi.assessments-domain}/financial-assessments/
    search-url: ${maatApi.assessments-domain}/financial-assessments/{financialAssessmentId}
  passport-assessment-endpoints:
    find-url: ${maatApi.assessments-domain}/passport-assessments/repId/{repId}
  hardship-review-endpoints:
    find-url: ${maatApi.assessments-domain}/hardship/repId/{repId}
  ioj-appeal-endpoints:
    find-url: ${maatApi.assessments-domain}/ioj-appeal/repId/{repId}
  rep-order-endpoints:
    find-url: ${maatApi.assessments-domain}/rep-orders/{repId}
    date-completion-url: ${maatApi.assessments-domain}/rep-orders/update-date-completed

means-assessment:
  security:
    issuer-uri: http://localhost:${server.port}

spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST_PORT}/${DATASOURCE_DBNAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 3600000

  security:
    oauth2:
      client:
        provider:
          maat-api:
            token-uri: ${MAAT_API_OAUTH_URL}
        registration:
          maat-api:
            client-id: ${MAAT_API_OAUTH_CLIENT_ID}
            client-secret: ${MAAT_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials

      resource-server:
        jwt:
          issuer-uri: ${means-assessment.security.issuer-uri}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

springdoc:
  packagesToScan: uk.gov.justice.laa.crime.meansassessment
  api-docs:
    path: /open-api/api-docs

  swagger-ui:
    operationsSorter: method

sentry:
  dsn: https://f6f14768c95b4cc38f597ebd5cfd0129@o345774.ingest.sentry.io/6212907
  environment: ${SENTRY_ENV}
  release: 0.0.1
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: true
  sample-rate: 0.05

retry-config:
  max-retries: 3
  min-back-off-period: 5
  jitter-value: 0.75

version: 0.0.1
