server:
  port: 8080

logging:
  level:
    root: ${LOG_LEVEL}
    org.springframework.web: ${LOG_LEVEL}
    org.springframework.security: ${LOG_LEVEL}

management:
  server:
    port: 8096
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    propagation:
      type: w3c,b3

maatApi:
  baseUrl: ${MAAT_API_BASE_URL}
  registrationId: maat-api


spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST_PORT}/${DATASOURCE_DBNAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 3600000

  security:
    oauth2:
      client:
        provider:
          maat-api:
            token-uri: ${MAAT_API_OAUTH_URL}
        registration:
          maat-api:
            client-id: ${MAAT_API_OAUTH_CLIENT_ID}
            client-secret: ${MAAT_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials

      resource-server:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

springdoc:
  packagesToScan: uk.gov.justice.laa.crime.meansassessment
  api-docs:
    path: /open-api/api-docs

  swagger-ui:
    path: /open-api/swagger-ui/index.html
    operationsSorter: method

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENV}
  release: 0.0.1
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: true
  sample-rate: ${SENTRY_SAMPLE_RATE}

retry-config:
  max-retries: 3
  min-back-off-period: 5
  jitter-value: 0.75

version: 0.0.1
