server:
  port : 8080
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
  sql:
    init:
      platform: postgres

springdoc:
  packagesToScan: uk.gov.justice.laa.crime.meansassessment
  show-actuator: true
  api-docs:
    path: /crime-means-assessment
    enabled: true

  swagger-ui:
    path: /open-api/docs.html
    enabled: true
    operationsSorter: method


sentry:
  dsn: https://27fa5ff9451241cc8cd9aa85dac09e60@o345774.ingest.sentry.io/5372961
  environment: ${SENTRY_ENV}
  release: 1.1.0
  servername: aws-ecs-container
  send-default-pii: true
  logging:
    minimum-breadcrumb-level: info
    minimum-event-level: info
    enabled: true
  attach-stacktrace: true

feature:
  postMvpEnabled: ${POST_MVP_ENABLED}

version: 0.0.1
