server:
  port : 8080


maatApi:
  validationUrl: " "
spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST_PORT}/${DATASOURCE_DBNAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 3600000

  security:
    oauth2:
      client:
        provider:
          maatapi:
            tokenUri:
        registration:
          maatapi:
            clientId:
            clientSecret:
            authorizationGrantType: client_credentials




  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false   

springdoc:
  packagesToScan: uk.gov.justice.laa.crime.meansassessment
  show-actuator: true
  api-docs:
    path: /crime-means-assessment
    enabled: true

  swagger-ui:
    path: /open-api/docs.html
    enabled: true
    operationsSorter: method


sentry:
  dsn: https://f6f14768c95b4cc38f597ebd5cfd0129@o345774.ingest.sentry.io/6212907
  environment: ${SENTRY_ENV}
  release: 0.0.1
  servername: aws-eks-container
  send-default-pii: true
  logging:
    minimum-breadcrumb-level: info
    minimum-event-level: info
    enabled: true
  attach-stacktrace: true


version: 0.0.1
