server:
  port : 8080

springdoc:
  packagesToScan: uk.gov.justice.laa.crime.meansassessment
  show-actuator: true
  api-docs:
    path: /crime-means-assessment
    enabled: true

  swagger-ui:
    path: /open-api/docs.html
    enabled: true
    operationsSorter: method


sentry:
  dsn: https://27fa5ff9451241cc8cd9aa85dac09e60@o345774.ingest.sentry.io/5372961
  environment: ${SENTRY_ENV}
  release: 1.1.0
  servername: aws-ecs-container
  send-default-pii: true
  logging:
    minimum-breadcrumb-level: info
    minimum-event-level: info
    enabled: true
  attach-stacktrace: true

feature:
  postMvpEnabled: ${POST_MVP_ENABLED}

version: 0.0.1
