server:
  port : 8080


maatApi:
  baseUrl: ${MAAT_API_BASE_URL}
  validation:
    endpoints:
      roleActionEndpoint: /authorization/users/{username}/actions/{action}
      newWorkReasonEndpoint: /authorization/users/{username}/work-reasons/{nworCode}
      reservationEndpoint: /authorization/users/{username}/reservations/{reservationId}/sessions/{sessionId}
      outstandingAssessmentsEndpoint: /financial-assessments/check-outstanding/{repId}
# The meansAssessment section is an example only
  meansAssessment:
    endpoints:
      create: /financial-assessments/
      update: /financial-assessments/{financialAssessmentId}
      get: /financial-assessments/{financialAssessmentId}


spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST_PORT}/${DATASOURCE_DBNAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 3600000

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

  security:
    oauth2:
      client:
        provider:
          maatapi:
            token-uri: http://dummyserver:9999
        registration:
          maatapi:
            client-id: dummy-client
            client-secret: dummy-secret


springdoc:
  packagesToScan: uk.gov.justice.laa.crime.meansassessment
  show-actuator: true
  api-docs:
    path: /crime-means-assessment
    enabled: true

  swagger-ui:
    path: /open-api/docs.html
    enabled: true
    operationsSorter: method


sentry:
  dsn: https://27fa5ff9451241cc8cd9aa85dac09e60@o345774.ingest.sentry.io/5372961
  environment: ${SENTRY_ENV}
  release: 1.1.0
  servername: aws-eks-container
  send-default-pii: true
  logging:
    minimum-breadcrumb-level: info
    minimum-event-level: info
    enabled: true
  attach-stacktrace: true

version: 0.0.1
