--liquibase formatted sql
--changeset rajeshk:04-assessment-criteria-table-create
CREATE TABLE IF NOT EXISTS crime_means_assessment.ASSESSMENT_CRITERIA
(
	ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	DATE_FROM TIMESTAMP NOT NULL,
	INITIAL_LOWER_THRESHOLD DECIMAL(12,2) NOT NULL,
	INITIAL_UPPER_THRESHOLD DECIMAL(12,2) NOT NULL,
	FULL_THRESHOLD DECIMAL(12,2) NOT NULL,
	APPLICANT_WEIGHTING_FACTOR DECIMAL(4,2) NOT NULL,
	PARTNER_WEIGHTING_FACTOR DECIMAL(4,2) NOT NULL,
	DATE_CREATED TIMESTAMP NOT NULL,
	CREATED_BY VARCHAR(10) NOT NULL,
	DATE_TO TIMESTAMP,
	DATE_MODIFIED TIMESTAMP,
	MODIFIED_BY VARCHAR(10),
	LIVING_ALLOWANCE DECIMAL(12,2),
	ELIGIBILITY_THRESHOLD DECIMAL(12,2),
    CONSTRAINT PK_ASSESSMENT_CRITERIA PRIMARY KEY (ID)
);