--liquibase formatted sql
--changeset lucast:06-ass-criteria-child-weightings-table-create
CREATE TABLE IF NOT EXISTS crime_means_assessment.ass_criteria_child_weightings
(
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ass_criteria_id INTEGER NOT NULL,
    lower_age_range INTEGER NOT NULL,
    upper_age_range INTEGER NOT NULL,
    weighting_factor DECIMAL(4,2) NOT NULL,
    date_created TIMESTAMP NOT NULL,
    user_created VARCHAR(10) NOT NULL,
    date_modified TIMESTAMP,
    user_modified VARCHAR(10),

    CONSTRAINT pk_ass_criteria_child_weightings PRIMARY KEY (ID),
    CONSTRAINT assessment_criteria_fk FOREIGN KEY (ass_criteria_id)
        REFERENCES crime_means_assessment.assessment_criteria (id)
);