--liquibase formatted sql
--changeset rajeshk:14-case-type-ass-detail-values-table-create
CREATE TABLE IF NOT EXISTS crime_means_assessment.case_type_ass_detail_values
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    caty_case_type VARCHAR(20),
    acrd_id BIGINT NOT NULL,
    applicant_value DECIMAL(10,2),
    partner_value DECIMAL(10,2),
    applicant_freq_code VARCHAR(20),
    partner_freq_code VARCHAR(20),
    date_created TIMESTAMP DEFAULT current_timestamp NOT NULL,
    created_by VARCHAR(100) DEFAULT current_user NOT NULL,
    date_modified TIMESTAMP,
    modified_by VARCHAR(100),

    CONSTRAINT pk_case_type_ass_detail_values PRIMARY KEY (id),
    CONSTRAINT uk_ctadv_catycasetype_acrdid UNIQUE (caty_case_type, acrd_id),
    CONSTRAINT fk_ctadv_acrd FOREIGN KEY (acrd_id)
    REFERENCES ass_criteria_details (id)
);