--liquibase formatted sql
CREATE TABLE IF NOT EXISTS crime_means_assessment.income_evidence
(
    "EVIDENCE" VARCHAR2(20 BYTE),
    "DESCRIPTION" VARCHAR2(100 BYTE),
    "DATE_CREATED" TIMESTAMP (6),
    "USER_CREATED" VARCHAR2(100 BYTE),
    "DATE_MODIFIED" TIMESTAMP (6),
    "USER_MODIFIED" VARCHAR2(100 BYTE),
    "LETTER_DESCRIPTION" VARCHAR2(500 BYTE),
    "WELSH_LETTER_DESCRIPTION" VARCHAR2(500 BYTE),
    "ADHOC" VARCHAR2(1 BYTE) DEFAULT 'N',
    CONSTRAINT pk_income_evidence PRIMARY KEY (EVIDENCE)
);