--liquibase formatted sql
--changeset muthus:21-income-evidence-table-insert
Insert into crime_means_assessment.income_evidence (EVIDENCE,DESCRIPTION,DATE_CREATED,USER_CREATED,DATE_MODIFIED,USER_MODIFIED,LETTER_DESCRIPTION,WELSH_LETTER_DESCRIPTION,ADHOC) values ('SIGNATURE','Signature',to_timestamp('20-DEC-10 20.23.24.644928000','DD-MON-RR HH24.MI.SSXFF'),'crime_means_assessment',null,null,'Signature','Llofnod','N');
Insert into crime_means_assessment.income_evidence (EVIDENCE,DESCRIPTION,DATE_CREATED,USER_CREATED,DATE_MODIFIED,USER_MODIFIED,LETTER_DESCRIPTION,WELSH_LETTER_DESCRIPTION,ADHOC) values ('CDS15','CDS 15',to_timestamp('29-FEB-12 17.10.04.000000000','DD-MON-RR HH24.MI.SSXFF'),'TASK343',null,null,'CDS 15','CDS 15','Y');
Insert into crime_means_assessment.income_evidence (EVIDENCE,DESCRIPTION,DATE_CREATED,USER_CREATED,DATE_MODIFIED,USER_MODIFIED,LETTER_DESCRIPTION,WELSH_LETTER_DESCRIPTION,ADHOC) values ('FREEZING','Freezing order',to_timestamp('29-FEB-12 17.10.04.000000000','DD-MON-RR HH24.MI.SSXFF'),'TASK343',null,null,'Freezing order','Gorchymyn Rhewi','Y');
Insert into crime_means_assessment.income_evidence (EVIDENCE,DESCRIPTION,DATE_CREATED,USER_CREATED,DATE_MODIFIED,USER_MODIFIED,LETTER_DESCRIPTION,WELSH_LETTER_DESCRIPTION,ADHOC) values ('RESTRAINING','Restraint Order',to_timestamp('29-FEB-12 17.10.04.000000000','DD-MON-RR HH24.MI.SSXFF'),'TASK343',to_timestamp('29-FEB-12 17.50.33.000000000','DD-MON-RR HH24.MI.SSXFF'),'LSC_TASK_651','Restraint Order','Gorchymyn Atal','Y');
Insert into crime_means_assessment.income_evidence (EVIDENCE,DESCRIPTION,DATE_CREATED,USER_CREATED,DATE_MODIFIED,USER_MODIFIED,LETTER_DESCRIPTION,WELSH_LETTER_DESCRIPTION,ADHOC) values ('CONFISCATION','Confiscation order',to_timestamp('29-FEB-12 17.10.04.000000000','DD-MON-RR HH24.MI.SSXFF'),'TASK343',null,null,'Confiscation order','Gorchymyn Atafaeliad','Y');
Insert into crime_means_assessment.income_evidence (EVIDENCE,DESCRIPTION,DATE_CREATED,USER_CREATED,DATE_MODIFIED,USER_MODIFIED,LETTER_DESCRIPTION,WELSH_LETTER_DESCRIPTION,ADHOC) values ('OTHER_ADHOC','Other Adhoc',to_timestamp('29-FEB-12 17.10.04.000000000','DD-MON-RR HH24.MI.SSXFF'),'TASK343',null,null,'Other Adhoc','Ad Hoc eraill','Y');
Insert into crime_means_assessment.income_evidence (EVIDENCE,DESCRIPTION,DATE_CREATED,USER_CREATED,DATE_MODIFIED,USER_MODIFIED,LETTER_DESCRIPTION,WELSH_LETTER_DESCRIPTION,ADHOC) values ('EMP LETTER ADHOC','Letter from Employer',to_timestamp('29-FEB-12 17.10.04.000000000','DD-MON-RR HH24.MI.SSXFF'),'TASK343',null,null,'Letter from Employer','Llythyr o''r cyflogwr','Y');
Insert into crime_means_assessment.income_evidence (EVIDENCE,DESCRIPTION,DATE_CREATED,USER_CREATED,DATE_MODIFIED,USER_MODIFIED,LETTER_DESCRIPTION,WELSH_LETTER_DESCRIPTION,ADHOC) values ('WAGE SLIP ADHOC','Wage Slip',to_timestamp('29-FEB-12 17.10.04.000000000','DD-MON-RR HH24.MI.SSXFF'),'TASK343',null,null,'Wage Slip within past 3 months','Papur Cyflog o fewn y tri mis diwethaf','Y');
Insert into crime_means_assessment.income_evidence (EVIDENCE,DESCRIPTION,DATE_CREATED,USER_CREATED,DATE_MODIFIED,USER_MODIFIED,LETTER_DESCRIPTION,WELSH_LETTER_DESCRIPTION,ADHOC) values ('NINO','National Insurance Number',to_timestamp('06-MAR-10 08.32.43.848894000','DD-MON-RR HH24.MI.SSXFF'),'crime_means_assessment',null,null,'National Insurance Number','Rhif Yswiriant Cenedlaethol','N');
Insert into crime_means_assessment.income_evidence (EVIDENCE,DESCRIPTION,DATE_CREATED,USER_CREATED,DATE_MODIFIED,USER_MODIFIED,LETTER_DESCRIPTION,WELSH_LETTER_DESCRIPTION,ADHOC) values ('ACCOUNTS','Set of Accounts',to_timestamp('06-MAR-10 08.32.43.849831000','DD-MON-RR HH24.MI.SSXFF'),'crime_means_assessment',null,null,'Set of Accounts','Cyfrifon','N');
Insert into crime_means_assessment.income_evidence (EVIDENCE,DESCRIPTION,DATE_CREATED,USER_CREATED,DATE_MODIFIED,USER_MODIFIED,LETTER_DESCRIPTION,WELSH_LETTER_DESCRIPTION,ADHOC) values ('OTHER BUSINESS','Other Business Records',to_timestamp('06-MAR-10 08.32.43.850347000','DD-MON-RR HH24.MI.SSXFF'),'crime_means_assessment',null,null,'Other Business Records','Cofnodion Busnes eraill','N');
Insert into crime_means_assessment.income_evidence (EVIDENCE,DESCRIPTION,DATE_CREATED,USER_CREATED,DATE_MODIFIED,USER_MODIFIED,LETTER_DESCRIPTION,WELSH_LETTER_DESCRIPTION,ADHOC) values ('CASH BOOK','Cash Book',to_timestamp('06-MAR-10 08.32.43.850854000','DD-MON-RR HH24.MI.SSXFF'),'crime_means_assessment',null,null,'Cash Book','Llyfr Arian','N');
Insert into crime_means_assessment.income_evidence (EVIDENCE,DESCRIPTION,DATE_CREATED,USER_CREATED,DATE_MODIFIED,USER_MODIFIED,LETTER_DESCRIPTION,WELSH_LETTER_DESCRIPTION,ADHOC) values ('WAGE SLIP','Wage Slip',to_timestamp('06-MAR-10 08.32.43.851367000','DD-MON-RR HH24.MI.SSXFF'),'crime_means_assessment',null,null,'Wage Slip within past 3 months','Papur Cyflog o fewn y tri mis diwethaf','N');
Insert into crime_means_assessment.income_evidence (EVIDENCE,DESCRIPTION,DATE_CREATED,USER_CREATED,DATE_MODIFIED,USER_MODIFIED,LETTER_DESCRIPTION,WELSH_LETTER_DESCRIPTION,ADHOC) values ('BANK STATEMENT','Bank Statement',to_timestamp('06-MAR-10 08.32.43.851898000','DD-MON-RR HH24.MI.SSXFF'),'crime_means_assessment',null,null,'Bank Statement(s) covering 3 months','Cyfriflen Banc','N');
Insert into crime_means_assessment.income_evidence (EVIDENCE,DESCRIPTION,DATE_CREATED,USER_CREATED,DATE_MODIFIED,USER_MODIFIED,LETTER_DESCRIPTION,WELSH_LETTER_DESCRIPTION,ADHOC) values ('TAX RETURN','Tax Return',to_timestamp('06-MAR-10 08.32.43.852422000','DD-MON-RR HH24.MI.SSXFF'),'crime_means_assessment',null,null,'Tax Return','Ffurflen Dreth','N');
Insert into crime_means_assessment.income_evidence (EVIDENCE,DESCRIPTION,DATE_CREATED,USER_CREATED,DATE_MODIFIED,USER_MODIFIED,LETTER_DESCRIPTION,WELSH_LETTER_DESCRIPTION,ADHOC) values ('EMP LETTER','Letter from Employer',to_timestamp('06-MAR-10 08.32.43.852931000','DD-MON-RR HH24.MI.SSXFF'),'crime_means_assessment',null,null,'Letter from Employer','Llythyr oddi wrth Gyflogwr','N');
Insert into crime_means_assessment.income_evidence (EVIDENCE,DESCRIPTION,DATE_CREATED,USER_CREATED,DATE_MODIFIED,USER_MODIFIED,LETTER_DESCRIPTION,WELSH_LETTER_DESCRIPTION,ADHOC) values ('OTHER','Other Ad-hoc evidence',to_timestamp('19-APR-11 17.06.06.000000000','DD-MON-RR HH24.MI.SSXFF'),'crime_means_assessment',null,null,'Text to be entered',null,'N');
