version: "3.2"

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
      - "8096:8096"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13.5
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
